### ISSUE TITLE
Queries with partial matching throw an error

### ISSUE THREAD

**Issue by areyesq89** [ComunidadBioInfo/regutools#4]
Queries with partial matching are throwing errors. Could not figure out what was exactly the problem. Maybe @jemilianosf or @CarBarJon have ideas of what could be happening?

Using the master version (commit 603626b2ca8036ecdb641b3d25d07e31bb1240c2):

```
> download_database(getwd())
trying URL 'https://www.dropbox.com/s/3xg6b2c0era21q8/regulondb_sqlite3.db?dl=1'
Content type 'application/binary' length 32411648 bytes (30.9 MB)
==================================================
downloaded 30.9 MB

> ecoli_regulondb <- 
+     regulondb(
+         database_path = file.path( getwd(), "regulondb_sqlite3.db" ),
+         organism="E.coli", database_version="version 1", 
+         genome_version="version 1" )
> get_dataset( ecoli_regulondb, 
+              attributes=c("posright","name"),
+              filters=list("name"="ara"),
+              partialmatch ="name",
+              dataset="GENE" )
 Error: Two values in the interval filter are required. 
```

**Comment by jemilianosf** [comment]
I'm checking this.

**Comment by jemilianosf** [comment]
I think the problem was that in the function that builds the query when there are no interval filters, if there is a partial match filter there is a call to the existing_partial_match function, but in the code there were  calls to existing_interval instead.

I replaced it and pushed to master (e15b6af).
